---
abstract: 'Atom Service Document object'
author:
  - 'Takeru INOUE <takeru.inoue _ gmail.com>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Atom-Service
provides:
  XML::Atom::Atompub:
    file: lib/XML/Atom/Atompub.pm
  XML::Atom::Categories:
    file: lib/XML/Atom/Categories.pm
  XML::Atom::Collection:
    file: lib/XML/Atom/Collection.pm
  XML::Atom::Control:
    file: lib/XML/Atom/Atompub.pm
  XML::Atom::Service:
    file: lib/XML/Atom/Service.pm
    version: v0.16.1
  XML::Atom::Workspace:
    file: lib/XML/Atom/Workspace.pm
requires:
  XML::Atom: 0.27
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.16.1
