# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Atom-Service
version:      0.01
version_from: lib/XML/Atom/Service.pm
installdirs:  site
requires:
    XML::Atom:                     

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
